### ISSUE TITLE
CTRL+SHIFT+Z and CTRL+SHIFT+A not working

### ISSUE THREAD

**Issue by mdacunha90** [ivangabriele/vscode-git-automator#1]
Hello,

The keyboard shortcuts CTRL+SHIFT+Z and CTRL+SHIFT+A, don't do anything at all. All other keyboard shortcuts work. When I hit CTRL+SHIFT+P it displays Add & Commit the current file, but it doesn't work neither. I uninstalled all extensions and tried running just the extension GIT ADD &COMMIT and it didn't work. The only message I get is when I'm in the KEYBOARD SHORTCUTS window: Running the contributed command: 'extension.addAndCommitCurrentFile' failed.
![image](https://user-images.githubusercontent.com/16214003/37195171-ff6219ce-2371-11e8-9226-4169775ab035.png)

My configuration:
- Windows 7
- Swiss French keyboard (QWERTZ)
- VSC version 1.21.0
- GIT ADD & COMMIT version 1.4.1

**Comment by ivangabriele** [comment]
Sorry for the very late answer, I admit I missed this one. Are you sure your current directory is under Git (I mean working when you use the CLI) ? This is strange because I though I try-catched all the errors and this one doesn't seem to be caught.

**Comment by mdacunha90** [comment]
Hello, thanks for the reply. My directory is on Git, I also asked my collegues who work on the same directory and they don't have this issue. The only difference between their configuration, hardware, etc. and mine is that they have a French keyboard (AZERTY) and I have a Swiss French keyboard (QWERTZ).

**Comment by ivangabriele** [comment]
Whatever is your "real" keyboard layout, what counts is which keyboard you chose on your OS. I have a French keyboard myself and always set it up as a US one. Key bindings are just a declaration interpreted by VS Code, so I doubt they have a bug on something so critical.

Does it work when you use CTRL+SHIFT+Q instead of CTRL+SHIFT+A and CTRL+SHIFT+W instead of CTRL+SHIFT+Z ?

**Comment by mdacunha90** [comment]
No this doesn't work

**Comment by ivangabriele** [comment]
Could you upgrade to the last version (1.5.1) and try to add a file via CTRL+SHIFT+P ? It should show an error, that you can extend by clicking on the upward arrow on the notification.

**Comment by mdacunha90** [comment]
That's the message i get : 

![image](https://user-images.githubusercontent.com/16214003/40620741-2e7a8a4a-629a-11e8-8080-8518c8922958.png)

and CTRL + SHIFT + Z worked and displayed the same message

**Comment by ivangabriele** [comment]
Yes sorry all the dependencies started to mess up, so I removed all of them. Can you update again to the v1.5.4 please ?

**Comment by mdacunha90** [comment]
I updated, it's version 1.6 and now I don't get any message. CTRL + SHIFT + Z does nothing like before and CTRL + SHIFT + P --> Add&commit current file does also nothing.

**Comment by ivangabriele** [comment]
When you do "CTRL+SHIFT+P > Add & Commit Current File", don't you have a message in the bottom status bar telling "Warning: nothing to commit, did you save your changes ?". Because you need to have existing changes on the current file or it won't do anything.

**Comment by mdacunha90** [comment]
I tried it with changes and without changes on the current file and I don't get any message.
