### ISSUE TITLE
Allow to use vie CTRL+SHIFT+P command then search for the command name instead of using shortcuts

### ISSUE THREAD

**Issue by ajcastro** [ivangabriele/vscode-git-automator#2]
I am used to CTRL+SHIFT+P then search for the command name instead of using shortcuts. 
Also this way, I can still use the default shortcut bindings of vscode

**Comment by ivangabriele** [comment]
You can already do it, just type `>add` in the commands finder and you will find it:

![screenshot 2018-10-22 at 12 32 00](https://user-images.githubusercontent.com/5957876/47288490-a6afa480-d5f6-11e8-8adc-e449673516e2.png)
