### ISSUE TITLE
Enable commit signing

### ISSUE THREAD

**Issue by ghost** [ivangabriele/vscode-git-automator#37]
Hi, I've been messing around with the extension but unable to find a way to auto sign the commit while using the hotkeys. 

What I tried:
- I've enabled it on the editor using `git.enableCommitSigning` and it works if I commit manually through the GUI, but not with the extension hotkeys.
- Tried looking for `gaac.sign*` or `gaac.commit*` with no luck.

Am I missing something or is this feature not supported?

Thanks

**Comment by ivangabriele** [comment]
Hi @bedouinhunter

Auto-signing your commits should be setup within Git itself. You can see how to do that [there](https://stackoverflow.com/a/20628522/2736233). Once it's done it will just work since this extension runs Git commands as you would type them yourself in a term.
